name: SRMS GitHub Actions CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore Packages
        run: dotnet restore StudentResultApp/StudentResultApp.csproj

      - name: Build Application
        run: dotnet build StudentResultApp/StudentResultApp.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test StudentResultApp.Tests/StudentResultApp.Tests.csproj --configuration Release --filter "FullyQualifiedName!~StudentResultUiTests"

      - name: Publish Application
        run: dotnet publish StudentResultApp/StudentResultApp.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
         app_location: "./publish"
output_location: "wwwroot"
